# Site settings
title: Madeira
locale: de
partner:
  name: Insel mit einzigartiger Natur
  link: http://www.visitmadeira.pt/

description: >
  Vor der Nordwestküste Afrikas liegt die Inselgruppe Madeira mitten im Atlantik. Neben der gleichnamigen Hauptinsel gehören auch Porto Santo, Ilhas Desertas und Ilhas Selvagens dazu.



# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/2021/madeira" # the subpath of your site, e.g. /blog/
img:     "/de/2021/madeira/_assets/img"
css:     "/de/2021/madeira/_assets/css"
js:      "/de/2021/madeira/_assets/js"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
